### ISSUE TITLE
BindOnUse, BindOnEquip, BindOnPickup

### ISSUE THREAD

**Issue by NevendyND** [mk7a/ItemSoulBind#10]
1.1.0
Get plugin version with /ver ItemSoulBind
1.15.2
Get spigot version with /ver

**Plugin Configuration**
<details>
  <summary>config.yml</summary>
# When player interacts with an item with the register string in its lore, item will be soul bound to them
registerString: "%soulbind%"

# SPECIAL BINDS - items with relevant bind string will only be bound in the specified conditions
# Colour is ignored when checking for string. Case sensitive

# Binds when tool is used: used to break block, sword used to hit entity
bindOnUse: true
bouString: "&9Soul binds on use"
# Binds when armor is equipped through in-hand right click
bindOnEquip: true
boeString: "&9Soul binds on equip"
# Binds when item is picked up
bindOnPickup: true
bopString: "&9Soul binds on pickup"

# Disable soul bind particle+sound effects
disableEffects: false

# Display message in item lore of soul bound item
# Use %username% for player name placeholder
displayLoreMsg: true
loreMsg: "&9Soul bound to %username%"

# Log player detected with item soul bound to another player in console
consoleLogDetection: true

# Prevents placing soul bound blocks
preventPlacing: false

# Prevents crafting with soul bound items
preventCraft: false

# Prevents enchanting with soul bound items
preventEnchant: false

# Prevents anvil use with soul bound items
preventAnvil: false

# Blocks commands when soul bound item is held in hand
# Only provide the first part of the command, e.g. for "/auction sell" :
blockedCommands:
  - "auction"

# =======================
# Messages | use '&' for color codes
msgPrefix: "&8[&bSoul&3Bind&8]&r "
denyMsg: "&9This item is soul bound to another player"
detectedItemMessage: "&cAn item soul bound to another player was removed from your inventory. Event has been logged."
detectedItemBroadcast: "was detected with an item soul bound to another player."
noPermissionGeneric: "&cInsufficient permissions."
noPermissionBindOthers: "&cInsufficient permissions to bind for other players."
bindSuccess: "&aSoul bind complete."
bindErrorHeldItem: "You must be holding an item in your main hand."
bindErrorAlreadyBound: "This item is already soul bound."
bindErrorNoSuchPlayer: "No such player found online."
unbindErrorNotBound: "Item is not soul bound."
unbindSuccess: "&aSoul bind removed."
inventoryProcessSuccess: "&aProcessed inventory of "
craftDeny: "&cCannot craft with soul bound items."
enchantDeny: "&cCannot enchant soul bound items."
anvilDeny: "&cCannot use anvil on soul bound items."
foundItems: "&7Soul bound items found with another player have been returned to you. Use &b/returnItems &7to get them."
noItems: "You have no items to retrieve."
specialBindDone: "&aSpecial bind applied to item."
cmdBlocked: "&cCannot perform this command on a soul bound item."
# ======================

configVersionDoNotModify: 1.4
</details>

**To Reproduce**
Activate the Settings

**Expected behavior**
I activate the settings but jea it didn't work..

**Screenshots**
Its the same Video but jea i did the same thing
https://youtu.be/fPN3BM4L_ng

**Additional context**

**Comment by mk7a** [comment]
Are you OP? The `itemsoulbind.bypass` permission will prevent binding.

**Comment by NevendyND** [comment]
bindonpickup works without OP

But the other two's not

Here a Video
https://youtu.be/eCLD0ozvPdI

**Comment by mk7a** [comment]
What other plugins are you using on the server?

**Comment by NevendyND** [comment]
Good, after creating a Test-Server and testing it out its the same thing but

First, No OP, No Admin Group, Survival

i try another thing

First here is the Video: https://youtu.be/Cd7IAbbtJa8

I hit a grass with a "soulbind on use" sword, then it was soulbind. 
(For me its Rightclick/Leftclick for use but jea, a little bit confusing, can you maybe add this with Rightclick/Leftclick? or is use for you to hit stuff?, then for other items like "teleportation-scrolls" its "nah")
I tested it with a "Scroll" but you can't souldbind them with attacking something like the sword
you need to break something with this scroll.
My Teleportscrolls are need to rightclicked in hand so it would be nice if they get soulbind

[Seems Like Bug] Equip works now too but you need to equip them via Rightclick if you hold them in hand, it doesn't helps to lay it on the field (you can see it in the Video)


Something I noticed would be this, it has two "types" and would be great if both are then overwritten and not just one, but that doesn't have to be absolutely necessary.
It's just a suggestion.
(I know "bindonequip" is for Armor the other was "Bindonuse")
![hadhrh](https://user-images.githubusercontent.com/28860034/85151868-97ae4900-b254-11ea-8fa2-a46cc445fb41.PNG)
