### ISSUE TITLE
Players lose all items except soulbound items when dying in a keep inventory zone

### ISSUE THREAD

**Issue by NightFuryStrike** [mk7a/ItemSoulBind#12]
**Plugin version**
1.1.0
**Spigot Version**
Paper-29

**Plugin Configuration**
<details>
  <summary>File</summary>

registerString: "[Binds on Purchase]"

bindOnUse: true

bouString: "&e[Binds On Use]"

bindOnEquip: true

boeString: "&e[Binds On Equip]"

bindOnPickup: true

bopString: "&e[Binds On Pickup]"

disableEffects: false

displayLoreMsg: true

loreMsg: "&8Bound to: %username%"

consoleLogDetection: true

preventPlacing: false

preventCraft: false

preventEnchant: false

preventAnvil: false

blockedCommands:
  - "auction"

configVersionDoNotModify: 1.4
</details>

**Plugins List**
![image](https://user-images.githubusercontent.com/56176412/86206815-a42f7d00-bb43-11ea-9e61-d121f5621dc8.png)

**To Reproduce**
Steps to reproduce the behavior
Step 1: Install WorldEdit, WorldGuard, WorldGuardExtraFlags, ItemSoulBind
Step 2: Create a worldguard region, and set the region to have the keep-inventory flag set to true.
Step 3: Soulbind an item to yourself, and ensure you have the permission to keep the item on death.
Step 4: Put some other items in your inventory that are not soulbound.
Step 5: Allow your player to die within the keep inventory zone.
Step 6: Observe the loss of all items except for the soulbound items.

**Expected behavior**
The player should keep all of their items and not have them deleted due to it being a keep-inventory zone.

**Comment by mk7a** [comment]
✔️ Fixed in next release.
