### ISSUE TITLE
Compat Issue with TraderPlus

### ISSUE THREAD

**Issue by ZEROOblivious** [mk7a/ItemSoulBind#13]
![image](https://user-images.githubusercontent.com/32251194/88125756-f7727980-cb9d-11ea-85e7-b65436e75ad2.png)
![image](https://user-images.githubusercontent.com/32251194/88125769-fe998780-cb9d-11ea-8b02-940408baeaad.png)

**Plugin Configuration**
https://pastebin.com/BvWkMKBR

**Plugins List**
[plugin list.txt](https://github.com/mk7a/ItemSoulBind/files/4957425/plugin.list.txt)
https://www.spigotmc.org/resources/trade-%E2%9C%B1-trade-items-money-tokens-protection-blocks-and-more-in-an-elegant-gui-%E2%9C%B1-1-7-10-1-16-x.23138/
^ Trading Plugin

**To Reproduce**
1. Trade A Soulbind Item with a NON-Op'd player
2. Bound Item stays in the other's player inv <-- We don't want this.
3. When doing /returnitems <-- it does not return or leave players inv
4. Sometimes when doing /returnitem it duplicates the item that's bound. 

**Expected behavior**
Not being able to trade soulbind items, if that's possible. 

![image](https://user-images.githubusercontent.com/32251194/88125952-6c45b380-cb9e-11ea-95a3-7421d33514b9.png)
^ This was console/plugin noticing that (May) has a soulbind item that's not hers while (Jacob) noticed it duplicated itself 3 Times. 

Posted Same issue on the TradePlus Github
https://github.com/Trophonix/TradePlus/issues/59

**Comment by mk7a** [comment]
I am unable to compile the trading plugin from its source code due to a dependency being private. Please send jar file to mk7a-mc[ᴀᴛ]protonmail.com

**Comment by mk7a** [comment]
Fixed in v1.4.0
