### ISSUE TITLE
Item Dupe on /minecraft:give command

### ISSUE THREAD

**Issue by sxphirus** [mk7a/ItemSoulBind#14]
**Plugin version**
1.1.0

**Spigot Version**
git-Tuinity-"30ac89a" 1.16.2

**Plugin Configuration**
Default 

**Plugins List**
N/A

**To Reproduce**
/give (player) diamond_sword{display:{Lore:['[{"text":"%soulbind%","italic":false}]']},Enchantments:[{id:fire_aspect,lvl:3}],Unbreakable:1} 1

**Expected behavior**
Should only receive one sword, yet receive 2, one is soulbound, one has %soulbind%

**Screenshots**
Not required?

**Additional context**

**Comment by mk7a** [comment]
Successfully reproduced. Will look into fixing.
