### ISSUE TITLE
Bind items can be given to another player with dispenser

### ISSUE THREAD

**Issue by Augmented-Bersy** [mk7a/ItemSoulBind#16]
**Plugin version**
1.1.1
**Spigot Version**
git-paper-191

**Plugin Configuration**
https://hastebin.com/acowiqurun.yaml

**Plugins List**
![image](https://user-images.githubusercontent.com/66171971/95654032-d6b72180-0b05-11eb-93bf-ed4d5a148cd3.png)

**To Reproduce**
- Place bind armor in dispenser. Other player should step close and use it. He will get the armor

**Expected behavior**
Another player souldn't take the armor

**Comment by mk7a** [comment]
@Augmented-Bersy 

✔️ Fixed in next release.
