### ISSUE TITLE
Error spammed in Console

### ISSUE THREAD

**Issue by Aeyori** [mk7a/ItemSoulBind#2]
**Plugin version**
Get plugin version with /ver ItemSoulBind
1.0.1
**Spigot Version**
Get plugin version with /ver
Paper 161
**To Reproduce**
Steps to reproduce the behavior
Using Bow with Soublind key string
**Expected behavior**
**Screenshots**
If applicable, add screenshots to help explain your problem e.g. console error stacktrace
https://pastebin.com/qF517Zaz
This error keeps on spamming in console, not sure if there's a problem or not
**Additional context**

**Comment by mk7a** [comment]
Simple mistake, thanks for reporting. 
 https://github.com/mk7a/ItemSoulBind/releases/tag/v1.0.2
