### ISSUE TITLE
Server Administration can make custom items bound to player on pickup

### ISSUE THREAD

**Issue by FlsdMeat** [mk7a/ItemSoulBind#24]
Hello, 
     I am looking for a feature where say the server has custom items, but doesn't want players exchanging them amongst themselves. When say "God Tier Chestplate" is added to a players inventory, no one else is allowed to pick it up or take from container except that player. 
     I know your plugin supports all items, but it would suit better if whitelisting items where possible, and even in-game whitelisting items from administrative player hand.

**Comment by mk7a** [comment]
1. Add bind string to the item lore: `%soulbind%` (configurable)
2. Run command `/bindInvItems <player>` immediately after command to add item to inventory
