### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by Aeyori** [mk7a/ItemSoulBind#4]
**Plugin version**
Get plugin version with /ver ItemSoulBind
V. 1.0.2
**Spigot Version**
Get plugin version with /ver
Paper 1.15.2

**To Reproduce**
Steps to reproduce the behavior
Die with soulbound item
**Expected behavior**
Keep soulbound items in inventory

**Additional context**
I'm using the DeluxeCombat plugin and they have a grave system and when I die, the soulbound items do not stay in my inventory and is at the grave. I wasn't sure which dev to contact first so I'm sorry if this isn't an issue on your end.

**Comment by mk7a** [comment]
Please send a copy of the DeluxeCombat plugin for me to investigate. 
email: mk7a-mc[𝚊𝚝]protonmail.com

**Comment by Aeyori** [comment]
I just wanted to let you know that DeluxeCombat support is not needed anymore and that I'm looking for Dead Souls compatibility instead! 

https://www.spigotmc.org/resources/dead-souls.69409/

**Comment by mk7a** [comment]
I have found a fix that will ensure compatability with all similar gravestone plugins. New version will be released soon.

**Comment by mk7a** [comment]
https://github.com/mk7a/ItemSoulBind/releases/tag/v1.1.0
