### ISSUE TITLE
Trading with villagers %soulbind%

### ISSUE THREAD

**Issue by UnitedBagels** [mk7a/ItemSoulBind#6]
**Plugin version**
Version 1.0.2
**Spigot Version**
1.15.2-R0.1-SNAPSHOT

**To Reproduce**
Make a custom villager who trades an item with %soulbind% -- try picking up the purchased item.

**Expected behavior**
The item should be placed in the player's inventory and be bound after a call to /bindinvitems. Instead, the item snaps back to the trading menu and cannot be picked up.

**Comment by mk7a** [comment]
What plugin are you using for custom villagers?

**Comment by UnitedBagels** [comment]
I generated them using command blocks and /summon, so everything there is vanilla

**Comment by mk7a** [comment]
Could you share this command? Thanks

-------- Original Message --------

**Comment by UnitedBagels** [comment]
The first command generates the villager without the %soulbind% tag item (which seems to work), while the second one does have the tag, causing the item to snap back.

`/summon villager ~ ~1 ~ {VillagerData:{profession:farmer,level:99,type:plains},PersistenceRequired:1,NoAI:1,Offers:{Recipes:[{buy:{id:gold_nugget,Count:5},sell:{id:diamond_sword,Count:1},maxUses:9999999}]}}
`

`/summon villager ~ ~1 ~ {VillagerData:{profession:farmer,level:99,type:plains},PersistenceRequired:1,NoAI:1,Offers:{Recipes:[{buy:{id:gold_nugget,Count:5},sell:{id:diamond_sword,Count:1,tag:{display:{Lore:["\"%soulbind%\""]}}},maxUses:9999999}]}}`

**Comment by mk7a** [comment]
Fixed in next release. Thank you for reporting.

**Comment by mk7a** [comment]
https://github.com/mk7a/ItemSoulBind/releases/tag/v1.1.0
