### ISSUE TITLE
bind on use

### ISSUE THREAD

**Issue by Emthro** [mk7a/ItemSoulBind#7]
**Plugin version**
1.0.2
**Spigot Version**
Get spigot version with /ver
git-Paper-149
**To Reproduce**
/bindonuse
- use the item and item doesn't get bound to plater
also doesn't work when it is set as lore

**Expected behavior**
item gets bound to the player when it is used

**Comment by mk7a** [comment]
Please send the plugin configuration file and a list of plugins you are running

**Comment by Emthro** [comment]
![image](https://user-images.githubusercontent.com/66216555/84080417-2647de00-a9aa-11ea-9a07-fd896089e698.png)

https://hastebin.com/apixofoyep.makefile

**Comment by Emthro** [comment]
im trying to make it work through lore on mmoitems if that helps

**Comment by mk7a** [comment]
The paste seems to have expired. Please attach your config via google drive link or similar. Thank you.
